theme: jekyll-theme-tactile
title: Bob McDiarmid's Spotify Search App for General Assembly Coursework in Javascript
description: so much awesome is coming here you're not going to be able to process it.
